config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'projects#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  devise_for :managers, controllers: { registrations: 'users/registrations' }
  devise_for :developers, controllers: { registrations: 'users/registrations' }
  devise_for :qas, controllers: { registrations: 'users/registrations' }
  resources :projects do
    resources :bugs do
      member do
        post :assign_dev
        post :resolve
      end
      collection do
        get 'update_status'
      end
    end
  end
  get '/*path', to: 'projects#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  # VALIDATIONS
  validates :name, presence: true
  validates :user_id, numericality: true
  validates_with ProjectValidator

  # ASSOCIATIONS
  belongs_to :user
  has_and_belongs_to_many :users
  has_many :bugs, dependent: :destroy

  # FUNCTIONS
  def developers
    users.select(&:developer?)
  end

  def qas
    users.select(&:qa?)
  end

  def creator
    user
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]

  def index
    @projects = Project.all
    @user_projects = current_user.projects if current_user
    @dev_bugs = current_developer.assigned_bugs.has_not_ended if current_developer
    authorize @projects
  end

  def new
    @project = Project.new
    @devs, @qas = unassigned_user
    authorize @project
  end

  def create
    @project = ProjectCreator.call(params, current_manager)
    @users_projects = user_params
    authorize @project
    if @project.save
      add_user_to_projects(@users_projects, @project)
      flash[:notice] = 'Project Successfully Created'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @devs, @qas = unassigned_user
  end

  def update
    @users_projects = user_params
    authorize @project
    if @project.update(project_params)
      add_user_to_projects(@users_projects, @project)
      flash[:notice] = 'Project Successfully Updated'
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def show
    @devs = @project.developers
    @qas = @project.qas
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { flash[:notice] = 'Project was successfully destroyed.' }
      format.js
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'Project does not exist'
    redirect_to new_project_url
  end

  def project_params
    params.require(:project).permit(:name)
  end

  def user_params
    params.require(:project).permit(user_id: [])
  end

  def unassigned_user
    unassigned_users = User.where.not(id: @project.users.collect(&:id))
    devs = unassigned_users.by_title('Developer')
    qas = unassigned_users.by_title('Qa')
    [devs, qas]
  end

  def add_user_to_projects(users_projects, proj)
    users_projects = users_projects.values
    users_projects = users_projects[0].select!(&:present?)
    users_projects.each do |user|
      u = User.find_by(id: user)
      proj.users << u unless u.nil?
    end
  end

  def current_user
    current_manager || current_developer || current_qa
  end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/views/projects/_devindex.html.erb
<h3>Developer's Site</h3>
<h1>Hi, <%= current_developer.username %> </h1>

<h3>Your Projects</h3>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Name</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <% @user_projects.each do |project| %>
    <tbody id="delProj<%= project.id %>">
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to 'View Bugs', project_bugs_path(project) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Assigned Bugs</h3>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th>Title</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

    <% if @dev_bugs != nil%>
      <% @dev_bugs.each do |bug| %>
      <tbody id="dev_bug_table">
        <tr id="bug_<%= bug.id%>">
          <td><%= bug.title %></td>
          <td><%= bug.project.name %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name,  class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :developers, "Software Developers",  class: "form-label" %>
    <%= form.collection_select :user_id,  @devs, :id, :username, {include_blank: false}, {multiple: true} %>
    <%= form.label :qas, "Software Quality Assurance Engineers", class: "form-label" %>
    <%= form.collection_select :user_id, @qas, :id, :username, {include_blank: false}, {multiple: true} %>
  </div>

  <%= form.submit "Submit", class: "btn btn-default btn-primary" %>
<% end %>

app/views/projects/_managerindex.html.erb
<h1>Hi, <%= current_manager.username %> </h1>
<h3>Manager</h3>

<button type="button" class="btn btn-light"><%= link_to 'Create a new project', new_project_path %></button>

<h1>Your Projects</h1>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Name</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <% @projects.each do |project| %>
    <tbody id="delProj<%= project.id %>">
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/_qaindex.html.erb
<h1>Software Quality Assurance</h1>
<h1>Hi, <%= current_user.username %> </h1>
<%= puts current_qa.username %>

<h3>Your Projects</h3>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Name</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <% @user_projects.each do |project| %>
    <tbody id="delProj<%= project.id %>">
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to 'Report a bug', new_project_bug_path(project) %></td>
        <td><%= link_to 'View Bugs', project_bugs_path(project) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>All Projects</h3>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Name</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <% @projects.each do |project| %>
    <tbody id="delProj<%= project.id %>">
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to 'Report a bug', new_project_bug_path(project)  %></td>
        <td><%= link_to 'View Bugs', project_bugs_path(project) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/destroy.js.erb
let element = document.querySelector("#delProj" + <%= @project.id %>);
element.remove();

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', root_path %>

app/views/projects/index.html.erb
<% if manager_signed_in? %>
 <%= render 'managerindex' %>
<% elsif developer_signed_in? %>
 <%= render 'devindex' %>
<% elsif qa_signed_in? %>
 <%= render 'qaindex' %>
<% else %>
  <div class = "jumbotron d-flex align-items-center">
    <div class="container">
      <h1>Welcome to Bugzilla!</h2>
    </div>
  </div>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', root_path %>

app/views/projects/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Developers Assigned</strong>
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">Name</th>
      </tr>
    </thead>

    <% @devs.each do |dev| %>
      <tbody>
        <tr>
          <td><%= dev.username %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</p>

<p>
  <strong>QA's Assigned</strong>
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">Name</th>
      </tr>
    </thead>

    <% @qas.each do |qa| %>
      <tbody>
        <tr>
          <td><%= qa.username %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', root_path %>