config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'projects#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  devise_for :managers, controllers: { registrations: 'users/registrations' }
  devise_for :developers, controllers: { registrations: 'users/registrations' }
  devise_for :qas, controllers: { registrations: 'users/registrations' }
  resources :projects do
    resources :bugs do
      member do
        post :assign_dev
        post :resolve
      end
      collection do
        get 'update_status'
      end
    end
  end
  get '/*path', to: 'projects#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bug.rb
# frozen_string_literal: true

class Bug < ApplicationRecord
  attr_accessor :remove_ss_image

  # VALIDATIONS
  validates :title, uniqueness: true
  validates :title, :status, :bug_type, presence: true
  validates :ss_image, attached: false, content_type: %i[png gif]
  validates_with BugValidator, unless: :has_reporter? || :has_assignee?

  # ENUMS
  enum bug_type: { feature: 0, bug: 1 }
  enum status: { New: 0, started: 1, ended: 2 }

  # ASSOCIATIONS
  belongs_to :project
  belongs_to :reporter, class_name: 'User'
  belongs_to :assignee, class_name: 'User', optional: true
  has_one_attached :ss_image

  # SCOPES
  scope :has_not_ended, -> { where.not(status: Bug.statuses[:ended]) }

  # FUNCTIONS
  def has_reporter?
    reporter.present?
  end

  def has_assignee?
    assignee.present?
  end
end

app/controllers/bugs_controller.rb
# frozen_string_literal: true

class BugsController < ApplicationController
  before_action :get_project
  before_action :set_bug, only: %i[show edit update destroy assign_dev resolve]

  def index
    @bugs = @project.bugs
    @d_bugs = @project.bugs.has_not_ended
    @dev_p_bugs = current_developer.assigned_bugs.has_not_ended.where(project_id: @project.id) if current_developer
  end

  def new
    @bug = @project.bugs.build
    authorize @bug
  end

  def create
    @bug = @project.bugs.build(bug_params)
    assign_qa
    authorize @bug
    if @bug.save
      flash[:notice] = 'Bug added successfully'
      redirect_to project_bugs_path(@project)
    else
      flash[:alert] = 'Bug failed'
      render 'new'
    end
  end

  def update
    authorize @bug
    if @bug.update(bug_params)
      flash[:notice] = 'Bug added successfully'
      redirect_to project_bugs_path(@project)
    else
      flash[:alert] = 'Bug failed'
      render 'new'
    end
  end

  def edit; end

  def show; end

  def destroy
    authorize @bug
    @bug.destroy
    respond_to do |format|
      format.html { flash[:notice] = 'Bug was successfully destroyed.' }
      format.js
    end
  end

  def update_status
    if params[:bugs].present?
      @status = if params[:bugs] == 'Feature'
                  { 'New' => 0, 'Started' => 1, 'Completed' => 2 }
                else
                  { 'New' => 0, 'Started' => 1, 'Resolved' => 2 }
                end
    end
    if request.xhr?
      respond_to do |format|
        format.json do
          render json: { status: @status }
        end
      end
    end
  end

  def assign_dev
    authorize @bug
    if current_developer
      if @bug.update(assignee_id: current_developer.id)
        respond_to do |format|
          format.html { redirect_to root_url, notice: 'Bug was successfully assigned.' }
          format.js
        end
      else
        flash[:alert] = 'Bug was not assigned.'
        redirect_to root_url
      end
    else
      flash[:alert] = 'User is not a developer'
    end
  end

  def resolve
    authorize @bug
    if current_developer
      if @bug.ended!
        respond_to do |format|
          format.html { flash[:notice] = 'Bug was successfully resolved.' }
          format.js
        end
      else
        flash[:alert] = 'Bug was not resolved.'
        redirect_to root_url
      end
    else
      flash[:alert] = 'User is not a developer'
    end
  end

  private

  def get_project
    @project = Project.find(params[:project_id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'Project does not exist'
    redirect_to new_project_url
  end

  def bug_params
    params.require(:bug).permit(:title, :deadline, :bug_type, :status, :remove_ss_image, :ss_image).tap do |p|
      p[:bug_type] = p[:bug_type].to_i if p[:bug_type]
      p[:status] = p[:status].to_i if p[:status]
    end
  end

  def assign_qa
    if current_qa
      @bug.reporter_id = @current_qa.id
    else
      flash[:alert] = 'QA not signed in'
      redirect_to new_user_session_path
    end
  end

  def set_bug
    @bug = @project.bugs.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'Bug does not exist'
    redirect_to new_project_bug_url
  end
end

app/helpers/bugs_helper.rb
# frozen_string_literal: true

module BugsHelper
end

app/views/bugs/_bug.html.erb
<tr>
        <td><%= bug.title %></td>
        <td><%= bug.project.name %></td>
        <td><%= link_to 'Mark as Resolved', resolve_project_bug_path(@project, bug), remote: true, method: :post, data: { confirm: 'Are you sure?' }   %></td>
      </tr>

app/views/bugs/_devindex.html.erb
<h3>Assigned Bugs</h3>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th>Title</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody id="dev_bug_table">
    <% if @dev_p_bugs != nil%>
      <% @dev_p_bugs.each do |bug| %>
        <tr id="bug_<%= bug.id%>">
          <td><%= bug.title %></td>
          <td><%= bug.project.name %></td>
          <td><%= link_to 'Mark as Resolved', resolve_project_bug_path(@project, bug), remote: true, method: :post, data: { confirm: 'Are you sure?' }   %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<h3>All Bugs</h3>


<table class="table">
  <thead class="thead-light">
    <tr>
      <th>Title</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

    <% @d_bugs.each do |bug| %>
    <tbody>
      <% if !(bug.has_assignee?) %>
        <tr id="bug_1_<%= bug.id%>">
          <td><%= bug.title %></td>
          <td><%= bug.project.name %></td>
          <td><%= link_to 'Assign Yourself',  assign_dev_project_bug_path(@project, bug), remote: true, method: :post %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

app/views/bugs/_form.html.erb
<%= form_with(model: [@project, bug], local: true) do |form| %>
  <% if bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bug.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
      <% bug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :title,  class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :deadline,  class: "form-label" %>
    <%= form.date_field :deadline, class: "form-control" %>
  </div>
    <div class="field">
    <%= form.label :ss_image %>
    <%= form.file_field :ss_image, direct_upload: true  %>
  </div>
  <div class="form-group", id="bugs">
    <%= form.label :bug_type,  class: "form-label" %>
    <%= select_tag 'bug[bug_type]', options_for_select(Bug.bug_types.map {|k, v| [k.humanize.capitalize, v]}), prompt: "Enter type", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :status,  class: "form-label" %>
    <%= select_tag 'bug[status]', options_for_select([]), prompt: "Enter status",  class: "form-control 'd-none",  id: "status" %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bugs/_qaindex.html.erb
<table class="table">
  <thead class="thead-light">
    <tr>
      <th>Title</th>
      <th>Project</th>
      <th colspan="5"></th>
    </tr>
  </thead>

    <% @bugs.each do |bug| %>
    <tbody id="delBug<%= bug.id %>">
      <tr>
        <td><%= bug.title %></td>
        <td><%= bug.project.name %></td>
        <td><%= link_to 'Show Project', [@project] %></td>
        <td><%= link_to 'Show', project_bug_path(@project, bug) %></td>
        <td><%= link_to 'Edit Bug', edit_project_bug_path(@project, bug) %></td>
        <td><%= link_to 'Destroy Bug', [@project, bug], method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bug', new_project_bug_path(@project) %>

app/views/bugs/assign_dev.js.erb
$("#dev_bug_table").append("<tr><%= j render @bug %></tr>");
var element = document.querySelector("#bug_1_" + <%= @bug.id %>);
element.remove();

app/views/bugs/destroy.js.erb
let element = document.querySelector("#delBug" + <%= @bug.id %>);
element.remove();

app/views/bugs/edit.html.erb
<h1>Editing Bug</h1>

<%= render 'form', project: @project, bug: @bug %>

<%= link_to 'Show', [@project, @bug] %> |
<%= link_to 'Back', root_path %>

app/views/bugs/index.html.erb
<h1>Bugs</h1>

<% if developer_signed_in? %>
 <%= render 'devindex' %>
<% elsif qa_signed_in? %>
 <%= render 'qaindex' %>
 <%end%>

app/views/bugs/new.html.erb
<h1>New Bug</h1>

<%= render 'form', project: @project, bug: @bug, status: @status %>

<%= link_to 'Back', root_path %>

app/views/bugs/resolve.js.erb
var element = document.querySelector("#bug_" + <%= @bug.id %>);
element.remove();

app/views/bugs/show.html.erb
<div class="container">
<p>
  <strong>Title:</strong>
  <%= @bug.title %>
</p>

<p>
  <strong>Type:</strong>
  <%= @bug.bug_type %>
</p>

<p>
  <strong>Status:</strong>
  <%= @bug.status %>
</p>


<p>
  <strong>Reporter:</strong>
  <%= @bug.reporter.username %>
</p>

<p>
  <strong>Assignee:</strong>
  <% if @bug.assignee.present? %>
    <%= @bug.assignee.username %>
  <% else %>
    Not assigned yet
  <% end %>
</p>

<p>
  <strong>Assignee:</strong>
  <% if @bug.ss_image.attached? %>
    <%= cl_image_tag(@bug.ss_image.key, width: 300, height: 200) %>
  <% else %>
    No image attached
  <% end %>
</p>

</div>

<%= link_to 'Edit', edit_project_bug_path(@project, @bug) %> |
<%= link_to 'Back', root_path %>